### ISSUE TITLE
Segmentation Fault on launch.

### ISSUE THREAD

**Issue by ghost** [martinohanlon/mayhem-pi#6]
Attempted to compile and run this on my Pi 3 running latest RetroPie.

All the source code files and the Makefile have DOS line endings for some reason. I compiled after running 'dos2unix *' on the directory. It appears to compile cleanly but I just get a segmentation fault on launch with no other information being written to the console.

**Comment by martinohanlon** [comment]
The project was originally developed for Windows, this is forked from that project, hence I suspect the reason for DOS line endings...

I suspect the segmentation fault is as a result of running dos2unix, gut feel says its probably an issue with the code being unable to load resources (bmp, wav).

**Comment by ghost** [comment]
I get the same segmentation fault even if I just run 'make clean' followed by 'make' without any dos2unix usage and a fresh checkout. Maybe a case sensitivity issue with the resources.

**Comment by martinohanlon** [comment]
Now that is wierd... I'll take a look, does it occur at a particular point, or is it as soon as you start the game?

Something comes to mind however - are you running the program from X-windows. The game engine, allegro, requires X to run. There is a script, start, which launches the program in X.

**Comment by martinohanlon** [comment]
Also as well as a requirement for X, the original code expect the working directory to be the same directory that the game is in - the start script also changes the working directory to the directory of the game prior to launching it.

**Comment by ghost** [comment]
I was not aware that the game used X as it isn't listed anywhere, nor is X used anywhere as a dependency. The game does appear to run with the start script.

**Comment by martinohanlon** [comment]
That's good.
